### ISSUE TITLE
Need ability to render <w:br/> 

### ISSUE THREAD

**Issue by Farhankazmi** [snowindy/scriptlet4docx#14]
Hi,

Thank you for your excellent scriptlet4docx library. One missing feature seems to be ability to support parameters that contains '\n'.  These need to be replaced with <w:br/> for appropriate rendering in most cases.

General suggestion, too much of the logic is private or package private.  I looked into extending the DocxTemplater class but it is closed to extension because of private methods.  I would suggest use of protected helper methods (similar to the Spring framework philosophy) for any significant logic that other might want to customize.

Thanks and Regards,
Farhan

**Comment by snowindy** [comment]
Thank you! I will add this feature soon.
I will also check if it's possible to make some steps protected as you request.

**Comment by snowindy** [comment]
Updated method definitions to be protected for possible extension. \n and \r\n are now rendered as < w:br />.

**Comment by snowindy** [comment]
version 0.8.3 will appear at maven central within several days.
