### ISSUE TITLE
Empty lines in the final document instead of blocks <% %>

### ISSUE THREAD

**Issue by Laiserg1k** [snowindy/scriptlet4docx#18]
A simple example:

**template**
Testing report
<% def a = “some text” %>
Some text.

**document**
Testing report

Some text.

**But I expected**
Testing report
Some text.

**Comment by snowindy** [comment]
Could you attach sample document with this? In fact I do not have a copy of MS Office :) I only have OpenOffice but it may not generate exact doc.

**Comment by Laiserg1k** [comment]
Yes, I attached the document.
[Test.docx](https://github.com/snowindy/scriptlet4docx/files/909508/Test.docx)

**Comment by Laiserg1k** [comment]
Добрый день! Приложил документ, не сразу отреагировал, был в отпуске.

2017-03-29 13:17 GMT+03:00 Eugene <notifications@github.com>:

**Comment by snowindy** [comment]
It's not a bug. Scriptlet is in a paragraph. Scriptlet code is not printed but the paragraph should not be removed, even if it's empty. If you would like not have new line - please place scriptlet in a previous paragraph with other text.
Overall, I would recommend all coding outside document. It's more clear.
